import sqlite3
conn = sqlite3.connect('train_cache.db')
sdah = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='SDAH'").fetchall())
knj = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='KNJ'").fetchall())
brp = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='BRP'").fetchall())
rha = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='RHA'").fetchall())
hwh = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='HWH'").fetchall())
bwn = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='BWN'").fetchall())
bdc = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='BDC'").fetchall())
skg = set(row[0] for row in conn.execute("SELECT train_number FROM station_trains WHERE station_code='SKG'").fetchall())

print(f'Station train counts:')
print(f'  SDAH={len(sdah)}, BRP={len(brp)}, RHA={len(rha)}, KNJ={len(knj)}')
print(f'  HWH={len(hwh)}, BDC={len(bdc)}, BWN={len(bwn)}, SKG={len(skg)}')
print()
print(f'SDAH line cross-matches:')
print(f'  SDAH+BRP: {len(sdah & brp)}')
print(f'  SDAH+BRP+RHA: {len(sdah & brp & rha)}')
print(f'  SDAH+BRP+RHA+KNJ: {len(sdah & brp & rha & knj)}')
print(f'  BRP+KNJ: {len(brp & knj)}')
print()
print(f'Main line cross-matches:')
print(f'  HWH+BDC: {len(hwh & bdc)}')
print(f'  HWH+BDC+BWN: {len(hwh & bdc & bwn)}')
print(f'  HWH+BDC+BWN+SKG: {len(hwh & bdc & bwn & skg)}')
print()
print(f'Sample SDAH+BRP trains:', list(sdah & brp)[:5])
print(f'Sample HWH+BDC+BWN trains:', list(hwh & bdc & bwn)[:5])
conn.close()
